server:
  port: 4646

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smash
    username: root
    password: v3033144
    driver-class-name: com.mysql.cj.jdbc.Driver

#spring:
#  datasource:
#    url: jdbc:mysql://133.130.88.165:3306/smash
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver